services:
  - type: web
    name: office-frontend
    env: docker
    plan: free
    region: singapore
    rootDir: frontend
    dockerContext: .
    dockerfilePath: Dockerfile
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: office-backend
    env: docker
    plan: free
    region: singapore
    rootDir: backend
    dockerContext: .
    dockerfilePath: Dockerfile
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
