services:
  - type: web
    name: office-frontend
    env: docker
    plan: free
    region: singapore
    dockerContext: ./frontend
    dockerfilePath: Dockerfile
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: office-backend
    env: docker
    plan: free
    region: singapore
    dockerContext: ./backend
    dockerfilePath: Dockerfile
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        value: ${MONGO_URI}
      - key: JWT_SECRET
        value: secret
